[[redirects]]
  from = "/benchmarks"
  to = "https://pnpm.io/benchmarks"
  status = 301
[[redirects]]
  from = "/chat"
  to = "https://discord.gg/CeZ7xK2bvJ"
  status = 301
[[redirects]]
  from = "/comp"
  to = "https://pnpm.io/installation#compatibility"
  status = 301
